### PR TITLE
chore: organize encodings, types by tiers

### PR DESCRIPTION
**Pull request by rjzak**
Is what you were thinking @npmccallum @jedisct1?
Which algorithms should be in which section?

Signed-off-by: Richard Zak <richard@profian.com>

### CODE REVIEW

**Comment by jedisct1** [comment]
We eventually proposed 4 different sections in the [list of algorithms](https://github.com/WebAssembly/wasi-crypto/blob/main/docs/wasi-crypto.md#algorithms)

required (rsa_*_2048_sha256, rsa_*_3072_sha384, rsa_*_4096_sha512, *sha*, *aes*)
recommended (chachapoly, p256, p384, x25519 & ed25519 should be there, they are all required by TLS 1.3)
optional (xoodyak, kyber)
reserved (xchachapoly, aegis, aes-cbc, aes-gcm-siv, aes-siv, whatever we think people may need)

**Comment by jedisct1** [comment]
Isn't Ed25519 FIPS compliant now? 

https://csrc.nist.gov/CSRC/media/Presentations/NIST-Status-Update-on-Elliptic-Curves-and-Post-Qua/images-media/moody-dustin-threshold-crypto-workshop-March-2019.pdf

    In addition, we are adding new elliptic curve signature algorithms (deterministic
    ECDSA and EdDSA) and new elliptic curves (Edwards25519 and Edwards448).

**Comment by npmccallum** [comment]
@jedisct1 It was added in the `FIPS 186-5` draft. However, it remains to be seen if it will be added in future editions.

**Comment by npmccallum** [comment]
@jedisct1 Further, numerous organizations will be governed by `186-4` for years to come. Not all institutions adopt the new standards immediately.

**Comment by rjzak** [comment]
* Which Kyber to list? https://pq-crystals.org/kyber/ And how is it stored?
* Could some of the blanks be filled in? I don't know how a lot of these algorithms work or how the data is represented.

**Comment by jedisct1** [comment]
Gimme a sec, I'm going to suggest a change to your PR

**Pull request merged**
